### ISSUE TITLE
Adding Windows Testing

### ISSUE THREAD

**Issue by 1313e** [telegraphic/hickle#101]
You mention in the README.md file (and its copy in the docs), what the installation details are for Linux and Mac.
However, they are the same for Windows as well (I know, as I mainly use Windows and `hickle` is used in my `prism` package).

For that reason, it might be a good idea to add automated testing for Windows as well by using AppVeyor, and simply remove the specified OS in the installation details. 
As I have experience with setting up AppVeyor (have done it for all my Python packages), do you want me to do that for you?

**Comment by telegraphic** [comment]
Please do! Adding better windows support would be awesome

**Comment by 1313e** [comment]
Btw, for PRISM, I use the following in the `setup.py` for single-sourcing my versioning:
```
# Read the __version__.py file
with open('prism/__version__.py', 'r') as f:
    vf = f.read()

# Obtain version from read-in __version__.py file
version = re.search(r"^_*version_* = ['\"]([^'\"]*)['\"]", vf, re.M).group(1)
```
Where obviously there is a file called `__version__.py` in the package itself.
You may want to do that as well for `hickle`, as it avoids having to write and update the version in the `setup.py` file.

**Comment by 1313e** [comment]
However, tests are now running on Windows as well.
You will have to register `hickle` on AppVeyor though, which does not really take that long.
