### ISSUE TITLE
Can't load simple numpy arrays

### ISSUE THREAD

**Issue by bryanhpchiang** [telegraphic/hickle#111]
I'm saving a dict of numpy arrays but I keep on getting a KeyError. Not sure why this is happening. 

Using Python3 and the following code:
```
import hickle
import numpy as np
d=hickle.load("audio_data.hkl")
```

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-f107309904a7> in <module>
      1 import hickle
      2 import numpy as np
----> 3 d=hickle.load("audio_data.hkl")

~/.local/lib/python3.5/site-packages/hickle/hickle.py in load(fileobj, path, safe)
    529                 py_container = PyContainer()
    530                 py_container.container_type = 'hickle'
--> 531                 py_container = _load(py_container, h_root_group)
    532                 return py_container[0][0]
    533 

~/.local/lib/python3.5/site-packages/hickle/hickle.py in _load(py_container, h_group)
    599         for h_name in h_keys:
    600             h_node = h_group[h_name]
--> 601             py_subcontainer = _load(py_subcontainer, h_node)
    602 
    603         sub_data = py_subcontainer.convert()

~/.local/lib/python3.5/site-packages/hickle/hickle.py in _load(py_container, h_group)
    599         for h_name in h_keys:
    600             h_node = h_group[h_name]
--> 601             py_subcontainer = _load(py_subcontainer, h_node)
    602 
    603         sub_data = py_subcontainer.convert()

~/.local/lib/python3.5/site-packages/hickle/hickle.py in _load(py_container, h_group)
    583         py_subcontainer = PyContainer()
    584         try:
--> 585             py_subcontainer.container_type = bytes(h_group.attrs['type'][0])
    586         except KeyError:
    587             raise

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/.local/lib/python3.5/site-packages/h5py/_hl/attrs.py in __getitem__(self, name)
     58         """ Read the value of an attribute.
     59         """
---> 60         attr = h5a.open(self._id, self._e(name))
     61 
     62         if is_empty_dataspace(attr):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5a.pyx in h5py.h5a.open()

KeyError: "Can't open attribute (can't locate attribute: 'type')"

**Comment by albanie** [comment]
Just in case it's useful for others, I get this error if there is a slash in any of the keys in the dictionary.
`hickle version: 3.4.6`

Minimum working example:
```
sample = {"will/break": 0}                                               
hickle.dump(sample, "/tmp/out.hickle")                                   
res = hickle.load("/tmp/out.hickle")                                     
*** KeyError: "Can't open attribute (can't locate attribute: 'type')"
```
