### ISSUE TITLE
Long import times of hickle

### ISSUE THREAD

**Issue by aeantipov** [telegraphic/hickle#114]
WSL machine, `import hickle` takes about 2 seconds.  
The culprit are automatically loaded pandas and astropy. 
Here's the profile.

![image](https://user-images.githubusercontent.com/1170855/66439526-d4972000-e9e4-11e9-8ad7-641f958e596b.png)

**Comment by telegraphic** [comment]
@aeantipov nice breakdown! Agreed this should be improved -- particularly if we wanted to add support for even more packages in the future, which would slow it down further.

When dumping, all relevant packages will already be loaded. So ideally, these pandas/astropy should only be loaded as required when reading hickle files. This will require a change in the `lookup.py` logic.
