### ISSUE TITLE
hickle fails to load a serialized function

### ISSUE THREAD

**Issue by DBerke** [telegraphic/hickle#119]
I used `hickle` to serialize a function, and tried to open it again in a different script, but got a rather cryptic error:

```Python
$ with h5py.File(hdf5_file, mode='a') as f:
      hickle.dump(model_func, f, path='/fitting_function')

$ with h5py.File(hdf5_file, 'r') as f:
      function = hickle.load(f, path='/fitting_function')
```
```
Traceback (most recent call last):
    function = hickle.load(f, path='/fitting_function')
  File "/Users/dberke/anaconda3/envs/varcon-py3.7/lib/python3.7/site-packages/hickle/hickle.py", line 531, in load
    py_container = _load(py_container, h_root_group)
  File "/Users/dberke/anaconda3/envs/varcon-py3.7/lib/python3.7/site-packages/hickle/hickle.py", line 601, in _load
    py_subcontainer = _load(py_subcontainer, h_node)
  File "/Users/dberke/anaconda3/envs/varcon-py3.7/lib/python3.7/site-packages/hickle/hickle.py", line 608, in _load
    subdata = load_dataset(h_group)
  File "/Users/dberke/anaconda3/envs/varcon-py3.7/lib/python3.7/site-packages/hickle/hickle.py", line 561, in load_dataset
    return load_fn(h_node)
  File "/Users/dberke/anaconda3/envs/varcon-py3.7/lib/python3.7/site-packages/hickle/loaders/load_python3.py", line 160, in load_pickled_data
    return pickle.loads(data[0])
ModuleNotFoundError: No module named '__builtin__'
```
(`model_func` is a simple custom quadratic function in this case.) @1313e has already diagnosed the cause and mentioned he has a fix in mind.

**Comment by 1313e** [comment]
Thanks for raising this issue, @DBerke.
Yeah, the problem here is that we use `dill` in order to serialize most objects in `hickle`, as it is capable of serializing many more objects than standard `pickle`, but (for whatever reason) we don't use `dill` in order to read back-in serialized objects.
This means that if we serialize an object with `dill` that `pickle` normally cannot serialize, then it will crash upon loading.

**Comment by 1313e** [comment]
@telegraphic I think the solution here is actually simply to solely use `dill` for everything.
I just checked, and `dill` is compatible with all Python versions that we are supporting.
Given that we already want to use `dill` anyways, as shown by this:
https://github.com/telegraphic/hickle/blob/66b9500cc5d813cecece260133ad1b6d4d5a2a4a/hickle/hickle.py#L56-L62
and that `dill` has been part of the requirements the entire time already, we can simply get rid of this and use `dill` all the time.

**Comment by DBerke** [comment]
Awesome, thanks for the quick fix!
