### ISSUE TITLE
Huge dict() object loads failed

### ISSUE THREAD

**Issue by Larryliu912** [telegraphic/hickle#121]
Hi,

I have hug dict() to save, about 430~MB, after saved it by hickle.

Loads failed:
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\hickle\hickle.py", line 531, in load
    py_container = _load(py_container, h_root_group)
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\hickle\hickle.py", line 601, in _load
    py_subcontainer = _load(py_subcontainer, h_node)
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\hickle\hickle.py", line 608, in _load
    subdata = load_dataset(h_group)
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\hickle\hickle.py", line 561, in load_dataset
    return load_fn(h_node)
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\hickle\loaders\load_python3.py", line 157, in load_pickled_data
    return pickle.loads(data[0])
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\dill\_dill.py", line 275, in loads
    return load(file, ignore, **kwds)
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\dill\_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "D:\Users\Cidge\Anaconda3\envs\research_env_final\lib\site-packages\dill\_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
_pickle.UnpicklingError: pickle data was truncated

Does hickle have any memory limitations like pickle?

**Comment by 1313e** [comment]
Hi @Larryliu912,

uhm, `hickle` should not have a problem with sizes like that.
May I ask what was stored inside of this dict?

**Comment by Larryliu912** [comment]
There are BERT sentence vectors, so it is like:

dict is defaultdict

list [ndarray ... ndarray ]

The shape of the ndarray is (768,)

The length of the list is about 80 - 140.

So, can you please tell me the maximum size hickle can save?

**Comment by 1313e** [comment]
`hickle` does not have a maximum size that it can save, at least not inherently.
Its size limits would be determined by either the size limits of `pickle` or HDF5.
If you are saving a dict containing just normal Python objects (like, integers, floats, strings, etc.), `pickle` should not be used at all, although it clearly was in your error message.

Can you give me a minimal reproducible example?

**Comment by telegraphic** [comment]
ah -- are you using `defaultdict` from the `collections` module? This is likely not recognized as an inbuilt type, so is being pickled instead using `dill`. Not sure why `dill` can't load it though?

The better fix would be to add support for `collections`...

**Comment by Larryliu912** [comment]
> ah -- are you using `defaultdict` from the `collections` module? This is likely not recognized as an inbuilt type, so is being pickled instead using `dill`. Not sure why `dill` can't load it though?
> 
> The better fix would be to add support for `collections`...

You are right! I check the code, it did use dill!

**Comment by Larryliu912** [comment]
> `hickle` does not have a maximum size that it can save, at least not inherently.
> Its size limits would be determined by either the size limits of `pickle` or HDF5.
> If you are saving a dict containing just normal Python objects (like, integers, floats, strings, etc.), `pickle` should not be used at all, although it clearly was in your error message.
> 
> Can you give me a minimal reproducible example?



> ah -- are you using `defaultdict` from the `collections` module? This is likely not recognized as an inbuilt type, so is being pickled instead using `dill`. Not sure why `dill` can't load it though?
> 
> The better fix would be to add support for `collections`...

But it did work for small size, which makes me confused

**Comment by 1313e** [comment]
> ah -- are you using `defaultdict` from the `collections` module? This is likely not recognized as an inbuilt type, so is being pickled instead using `dill`. Not sure why `dill` can't load it though?
> 
> The better fix would be to add support for `collections`...

I actually added support for subclasses of `dict` quite some time ago (part of PR #117), but that one is not complete yet.

**Comment by 1313e** [comment]
@Larryliu912 Can you give me an example for which using `defaultdict` with `hickle` fails currently?
Then I can check if with my experimental changes that are currently planned for v4.0.0, it does work.

**Comment by telegraphic** [comment]
@1313e nice, looking forward to PR #117!

@Larryliu912 I think this is some kind of issue with `dill` and large files. The lazy short-term workaround would be to convert your defaultdict to a regular dict (just `dict(d)` should do it), and store that. The longer-term is to wait for @1313e's PR.

**Comment by Larryliu912** [comment]
> @Larryliu912 Can you give me an example for which using `defaultdict` with `hickle` fails currently?
> Then I can check if with my experimental changes that are currently planned for v4.0.0, it does work.

How about made both HDF5 and hickle backup for my data, and then I think you can do experiments from that?

**Comment by 1313e** [comment]
> How about made both HDF5 and hickle backup for my data, and then I think you can do experiments from that?

Then I would not know how the file was generated.

**Comment by Larryliu912** [comment]
> @1313e nice, looking forward to PR #117!
> 
> @Larryliu912 I think this is some kind of issue with `dill` and large files. The lazy short-term workaround would be to convert your defaultdict to a regular dict (just `dict(d)` should do it), and store that. The longer-term is to wait for @1313e's PR.

Actually, the reason I used the defaultdict is it can generate small file. Then size of the ndarray in defaultdict is 96, but in dict() is 31xx, which is really strange. Do you know why?

**Comment by Larryliu912** [comment]
> > How about made both HDF5 and hickle backup for my data, and then I think you can do experiments from that?
> 
> Then I would not know how the file was generated.

I suppose you can generate the hickle backup from the normal HDF5 backup? Then what can I do for that?

**Comment by 1313e** [comment]
Given that one works and one does not, the reason can probably be found there.
For example, using a normal `dict` will not pickle the data stored in it, thus more metadata is saved to the HDF5-file, making it larger.

**Comment by Larryliu912** [comment]
> Given that one works and one does not, the reason can probably be found there.
> For example, using a normal `dict` will not pickle the data stored in it, thus more metadata is saved to the HDF5-file, making it larger.

https://drive.google.com/open?id=1bIZVWWVWQHKhK4fa-d_z7EQfLOzDnqDP
You can download them here
