### ISSUE TITLE
Documentation example lead to 404 web page

### ISSUE THREAD

**Issue by IsakFalk** [telegraphic/hickle#122]
I was directed to the [hickle TOC page](https://telegraphic.github.io/hickle/toc.html) and looking for how to load a `.hkl` file I found a link pointing to the URL [http://www.cs.jhu.edu/~s/musings/pickle.html](http://www.cs.jhu.edu/~s/musings/pickle.html), but this site 404's.

Fix: remove or update link.

**Comment by telegraphic** [comment]
:'(

Here's the internet archive version: https://web.archive.org/web/20150422204903/http://www.cs.jhu.edu/~s/musings/pickle.html

Might be better to just link to the pickle module, which states:
```
Warning: The pickle module is not intended to be secure against erroneous or maliciously constructed data. Never unpickle data received from an untrusted or unauthenticated source.
```
