### ISSUE TITLE
'track_times' argument for 'dump' has no use

### ISSUE THREAD

**Issue by 1313e** [telegraphic/hickle#130]
So, while I was going through the tests of the package a bit for the v4 release, I noticed that the tests for the `track_times` optional argument do not actually do anything, which you can see here (if `caching_dump` is never called before the `test_track_times` function, which is the case, then that test does nothing as `DUMP_CACHE` is empty): https://github.com/telegraphic/hickle/blob/5e8f6260d476553da675e88ebecb2a7287341a8d/hickle/tests/test_hickle.py#L340-L374
That is actually a good thing, as it would infinitely loop in Python 3 due to string representation differences.

However, I decided to check what exactly `track_times` does.
According to the [`h5py` documentation](http://docs.h5py.org/en/stable/high/group.html?highlight=track_times#Group.create_dataset), this argument is solely used for creating datasets; is set to `True` by default; and enables the saving of the creation timestamps.
It is rather unclear actually what that means or what impact it has, and it is not mentioned anywhere else in the documentation.

But, seeing as it is set to `True` by default, which is the same default as `dump` has in `hickle`, there is no point in specifically asking for its value.
Furthermore, `dump` already allows for additional `kwargs` to be provided that are passed to the `create_dataset` method, so if anyone ever wants to set `track_times` to a different value, they can.

Also, in `hickle`, the argument is described as making sure that repeated hickling results in different files.
This description itself is very vague as what that exactly means, as repeated hickling using the exact same script either always results in a different file (if the file was opened for writing and truncated, thus becoming a new file) or impossible (if it was not truncated, causing the data to already exist with the same name).

Given the above, I feel like that the argument has no use besides confusing the user, and should therefore be removed in both v3 and v4.
@telegraphic What is your opinion?

**Comment by telegraphic** [comment]
This was a specific feature request from a user -- the user wanted md5sums for identical data to be identical. Agreed that the documentation is confusing, as the use case was the opposite: allowing `md5sum` tests on files with identical contents.

**Comment by 1313e** [comment]
> This was a specific feature request from a user -- the user wanted md5sums for identical data to be identical. Agreed that the documentation is confusing, as the use case was the opposite: allowing `md5sum` tests on files with identical contents.

But it won't.
I tried it out myself: If I save the same data to the same file twice, the md5sum will be different, as it is impossible to save that data to the same location as well.
But, even then, we can simply remove the `track_times` argument, as one can simply provide `track_times=False` to `dump`.

**Comment by 1313e** [comment]
Alright, I finally found where that feature was requested (#13).
I think we can still remove the code for it, as the `kwargs` from `dump` and `load` are passed to basically all functions, and are always used when creating groups or datasets.
This would also make the code a bit cleaner.

**Comment by telegraphic** [comment]
Agreed that `**kwargs` will catch this and pass it on, so OK to remove
