### ISSUE TITLE
Q: how do I list all the paths in a .hkl file?

### ISSUE THREAD

**Issue by mingwugmail** [telegraphic/hickle#142]
Hi, I saw usage like this:
—————-
dump(a, "test.hkl", path="/test", mode="w")
dump(a, "test.hkl", path="/test2", mode="r+")
dump(a, "test.hkl", path="/test3", mode="r+")
dump(a, "test.hkl", path="/test4", mode="r+")

a = load("test.hkl", path="/test")
b = load("test.hkl", path="/test2")
c = load("test.hkl", path="/test3")
d = load("test.hkl", path="/test4")
——————

My question is: if I get a file test.hkl, how do I list all the paths in that file?

I didn’t find any api in the document.

Thanks

**Comment by 1313e** [comment]
Listing all the paths in an HDF5-file can be done simply with the following:
```python
print(file['/'].keys())     # Print all paths at root in an HDF5-file object called 'file'
```

Listing all the groups that were made by `hickle` is quite a bit harder, as `hickle` groups can be pretty much anywhere in an HDF5-file.
If you want to know if a specific path leads to a group made by `hickle`, you can either try opening it with `hickle` using the method you described or check if this group has the attributes `'HICKLE_VERSION'` and `'HICKLE_PYTHON_VERSION'` for `hickle` v4 files or the attribute `'CLASS'` with value `'hickle'` for `hickle` v3 files.


PS: In `hickle` v4, you can actually write to the same open HDF5-file multiple times using a context manager:
```python
with h5py.File('test.hkl', mode='w') as file:
    dump(a, file, path="/test")
    dump(a, file, path="/test2")
    dump(a, file, path="/test3")
    dump(a, file, path="/test4")
```
This avoids opening and closing the file multiple times for no reason.

**Comment by mingwugmail** [comment]
Thank you for the detailed explanation.

BTW, can we add this info to the doc?

**Comment by mingwugmail** [comment]
One more question:

does this example:
```
with h5py.File('test.hkl', mode='w') as file:
    dump(a, file, path="/test")
    dump(a, file, path="/test2")
    dump(a, file, path="/test3")
```

Also work with append mode, i.e `with h5py.File('test.hkl', mode='a') as file`, to add new items to existing hkl file?

**Comment by 1313e** [comment]
Oh yeah, it works with opening the file in any mode that allows for it to be edited, which includes appending.

**Comment by mingwugmail** [comment]
Thanks.
