### ISSUE TITLE
Show pickle timings with protocol=2 in README

### ISSUE THREAD

**Issue by mrocklin** [telegraphic/hickle#15]
Hey, nice project.  I really like seeing more options for the dump/load interface.

Your README shows timings that place pickle as much much slower than hickle.  I suspect that you're not using the `protocol=` keyword to dump.  Using this keyword `pickle` dumps numpy arrays in very close to their raw form, suffering almost no overhead.  

Some timings

```Python
In [1]: import numpy as np

In [2]: x = np.random.random((2000, 2000))

In [3]: import pickle

In [4]: f = open('foo.pkl', 'w')

In [5]: %time pickle.dump(x, f)  # slow by default
CPU times: user 2 s, sys: 274 ms, total: 2.27 s
Wall time: 2.74 s

In [6]: f = open('foo.pkl', 'w')

In [7]: %time pickle.dump(x, f, protocol=2)  # actually very fast
CPU times: user 18.8 ms, sys: 36 ms, total: 54.8 ms
Wall time: 55.6 ms

In [8]: import hickle

In [9]: f = open('foo.hkl', 'w')

In [10]: %time hickle.dump(x, f)  # a bit faster
dumping <type 'numpy.ndarray'> to file <HDF5 file "foo.hkl" (mode r+)>
CPU times: user 764 µs, sys: 35.6 ms, total: 36.4 ms
Wall time: 36.2 ms
```

**Comment by telegraphic** [comment]
Thanks @mrocklin, I've updated the readme with this info. You know if I had bothered to read the docs about `protocol=2` then I probably wouldn't have started this project! I'm glad that I have though, as there's a lot of other advantages to HDF5 that are pretty powerful (e.g. compression & chunking).
