### ISSUE TITLE
TypeError: string argument without an encoding

### ISSUE THREAD

**Issue by Mareeta26** [telegraphic/hickle#152]
Hi,
I created a hickle file using the command
`  hkl.dump(source_list, os.path.join(DATA_DIR, 'new_data_sources_' + split + '.hkl'))`

I tried to open it with :
```
    train_file = os.path.join(DATA_DIR, 'new_data_sources_val.hkl')
    X = hkl.load(train_file)
```
It gives me error: 
```
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/hickle/hickle.py", line 531, in load
    py_container = _load(py_container, h_root_group)
  File "/opt/anaconda3/envs/py39/lib/python3.9/site-packages/hickle/hickle.py", line 585, in _load
    py_subcontainer.container_type = bytes(h_group.attrs['type'][0])
TypeError: string argument without an encoding
```

hickle version: 3.4.5
python: 3.9.6

**Comment by ngohienduong** [comment]
same issue here

**Comment by telegraphic** [comment]
Hi @Mareeta26  and @ngohienduong ,

If you're using Py 3.9 I think this is probably related to issues using `h5py` >= 3 (see https://github.com/telegraphic/hickle/issues/143). 

We've addressed these issue in Hickle v5 (https://github.com/telegraphic/hickle/pull/149), for which we have a release candidate. This RC also addresses issues with newest version of numpy, and should be backward-compatible with older hickle files.

**Comment by telegraphic** [comment]
Pleased to say that we've just released v5, would you mind trying `pip install hickle==5.0.0.dev0` and see if the problem persists? 

If the error is still there, please let us know your OS, python version, and the output of `pip freeze` so we can see what package versions might be conflicting.

**Comment by hernot** [comment]
@Mareeta26 @ngohienduong  i would appriciate if you could verify that your issue does not occur on hickle 5. It is capable to load hickle 3.x and 4.x files in addtion to hickle 5 files.

**Comment by telegraphic** [comment]
Closing -- please reopen if still an issue.
