### ISSUE TITLE
Missing tag for v4.04 ?

### ISSUE THREAD

**Issue by chetmurthy** [telegraphic/hickle#159]
In pip's database, hickle is listed as version 4.0.4.   But I cannot find a tag for that version in the source repository.  Is there another repository, where I might find it?  B/c I'd like to checkout the precise commit for that release.

**Comment by telegraphic** [comment]
Looks like this was commit `ab7e036de702020adc6ea01dd2a65f490c999c9a`; I've added a tag https://github.com/telegraphic/hickle/releases/tag/v4.0.4
