### ISSUE TITLE
Error when writing astropy.Time objects with more than one dimension

### ISSUE THREAD

**Issue by steven-murray** [telegraphic/hickle#162]
When writing an `astropy.time.Time` object that contains an array with more than one dimension I get:

![image](https://user-images.githubusercontent.com/1272030/182260099-acabe80c-7811-47e2-b899-e7632b4415f7.png)

The error seems clear enough: it's iterating through the values in the array and trying to encode each one, but that iterator is actually returning sub-arrays. Maybe using `np.nditer` would be better?

**Comment by telegraphic** [comment]
This was an interesting one! I've pushed a fix and test to a branch, CI running now

**Comment by telegraphic** [comment]
Should now be fixed @steven-murray -- please reopen if not!
