### ISSUE TITLE
Hickle now in Debian 

### ISSUE THREAD

**Issue by telegraphic** [telegraphic/hickle#166]
Thanks to @EdwardBetts, hickle is now included in Debian (unstable) 🙏.

Mainly opening this issue to let @hernot, @1313e, and other devs know 🚀. I have just fixed a few outstanding issues and will bump to v5.0.2.

**Comment by hernot** [comment]
Ok should i than before final release of 5.0.2 also provide minor mostly convenience interface stuff provide you before release of 5.0.2. Most of those are left overs from making 5.0.2 which would have unnecessarily prolongated release process back then are not essential for working with hickle. Mainly interface cosmetics simplifying eg. utilization of hickle memoisation structures by individual loaders, or generating a more generic interface for using custom filters and filters with altered default values as proposed by @texadactyl in issue #154 and provided an implementaion in pr #156. Or should i postpone to a pr for 5.0.2?
