### ISSUE TITLE
`conda-forge` release is outdated (v3.4.5)

### ISSUE THREAD

**Issue by ma-sadeghi** [telegraphic/hickle#168]
https://anaconda.org/conda-forge/hickle

**Comment by telegraphic** [comment]
Hi, I'm having trouble getting the feedstock to work (it is like a Rube Goldberg machine). I may need some help 🤯

**Comment by telegraphic** [comment]
Looks like a knight in shining feedstock armor arrived and is getting this working: https://github.com/conda-forge/hickle-feedstock/pull/15

**Comment by ma-sadeghi** [comment]
Great, then this issue can be closed then!
