### ISSUE TITLE
Memory leak of hickle.load() in a loop

### ISSUE THREAD

**Issue by jsw2000** [telegraphic/hickle#173]
```
files=['file1', 'file2', ...]
for i in range(100000):
    a=hickle.load(files[i])
    print(i)
```
I'm running hickle.load() in a loop. However, I find memory leak during this procedure. The memory used get increasingly larger. variable 'a' should be abandoned after each iteration, so I want to ask how to solve the memory leak problem. I haved tried to add a=None and gc.collect() following instructions for pickle. But they all didn't work. 

> https://stackoverflow.com/questions/16288936/how-do-i-prevent-memory-leak-when-i-load-large-pickle-files-in-a-for-loop

**Comment by telegraphic** [comment]
After refreshing my memory on the `hickle.load` function, I suspect this would have to be an upstream bug in h5py. I'm going to close for now, but not opposed to the issue being reopened if it is a bona fide bug within `hickle` itself.
