### ISSUE TITLE
Failing test with NumPy 1.24+ due to np.float()

### ISSUE THREAD

**Issue by evilmav** [telegraphic/hickle#174]
The line https://github.com/telegraphic/hickle/blob/1072e563919de0f37b44c89c91fdc21879e7b937/hickle/tests/test_hickle.py#L745 fails with `AttributeError: module 'numpy' has no attribute 'float'` in the recent NumPy versions.

**Comment by telegraphic** [comment]
Thanks @evilmav for reporting -- looks like @EdwardBetts has a potential fix in #171
