### ISSUE TITLE
Calling `hickle.dump()` on a `NamedTuple[Any, Any, ..., pd.DataFrame]`

### ISSUE THREAD

**Issue by amorehead** [telegraphic/hickle#175]
Hello.

Thank you for making this awesome library open-source for us all. I had one question about Hickle 5.0.2 and Pandas DataFrames. Is it possible to `dump` e.g., a `NamedTuple` object in Python 3 that contains a `pd.DataFrame` within it? I noticed that naively trying to call `dump` on one of my custom objects of this type yielded a `SerializatedWarning`:

```python
SerializedWarning: 'DataFrame' type not understood, data is serialized:
```

After I `dumped` this file onto my local storage device and tried calling `hickle.load` on it, I encountered a `TypeError`:

```python
TypeError("__new__() missing 7 required positional arguments: ...
```

It seems like `hickle` is needing to "reconstruct" my NamedTuple object upon loading it from storage. Is this expected behavior, or is there a way I can avoid having to pass all required arguments (since they should already be contained in this local object)?

**Comment by telegraphic** [comment]
Hi @amorehead, might be a good use case for [hickleable](https://github.com/steven-murray/hickleable)?

**Comment by telegraphic** [comment]
(a todo: we should update README.md to point to hickleable!)

**Comment by amorehead** [comment]
Hey, @telegraphic. Thanks for pointing this library out to me. I was able to resolve this by correcting the constructor of this custom object I was trying to "hickle", but I'll look at hickleable as well in the future!
