### ISSUE TITLE
file locking

### ISSUE THREAD

**Issue by fleming79** [telegraphic/hickle#18]
Sorry for not being too precise but on some occasions I have found that the files are locked and inaccessible (locked) after loading or dumping. Terminating the python process releases the files.

**Comment by telegraphic** [comment]
I wonder if this is to do with issue https://github.com/telegraphic/hickle/issues/20, that I just patched? Otherwise, it's likely a problem with `h5py`

**Comment by telegraphic** [comment]
Closing this issue for now, as it hasn't resurfaced for quite some time, so assuming its a problem with `h5py` or file I/O. If it can be recreated we can reopen.
