### ISSUE TITLE
Can't dump to existing file.

### ISSUE THREAD

**Issue by mmckerns** [telegraphic/hickle#20]
Can't dump more than one object to a file… not good.

```
>>> import hickle
>>> import h5py
>>> f = h5py.File('test.hdf', 'w')
>>> import numpy as np   
>>> a = np.arange(5)
>>> 
>>> hickle.dump(a, f, 'w')
dumping <type 'numpy.ndarray'> to file <HDF5 file "test.hdf" (mode r+)>
>>> hickle.dump(a, f, 'w')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmckerns/lib/python2.7/site-packages/hickle.py", line 349, in dump
    h5f = file_opener(file, mode, track_times)
  File "/Users/mmckerns/lib/python2.7/site-packages/hickle.py", line 107, in file_opener
    raise FileError
hickle.FileErrorError: cannot open file. Please pass either a filename string, a file object, or a h5py.File
```

Fails for `w` mode and `a` mode.

**Comment by telegraphic** [comment]
Thanks, I've changed how the file opener behaves to better handle this.

Just to clarify: you can't "dump more than one object to a file" using `hickle` -- it's a quick helper just to dump single objects to file, similar to pickle. The objects can be dictionaries of numpy arrays:

      a = { 'a' : np.arange(5), 'b' : np.arange(6) }

But sequential dumping will overwrite the last:
    
    a, b = np.arange(5), np.arange(6)
    hickle.dump(a, 'test.hkl')
    hickle.dump(b, 'test.hkl')

This is as `hickle` writes to a dataset called `data` inside the `h5py` file. If you need more advanced options, I'd suggest using `h5py` directly.

**Comment by mmckerns** [comment]
Thanks for the update.   However, that's depressing.  For me to use `hickle` in `klepto`, it means that I either need to rewrite `hickle` to store multiple items in a single `hdf` file, or I need to treat a directory as a "database" and then use a `hdf` file for each entry... or I need to just "leverage" what I can and write my own.  I want both cases, but the first is not possible right now.

**Comment by telegraphic** [comment]
It sounds like what you're after would require a bit of an overhaul of `hickle`. It's not something that the standard python `pickle` does as far as I'm aware. 

However I do love the idea of allowing multiple things to be pickled in one hdf5 file. I've been meaning to do a pretty comprehensive refactor of hickle, but haven't had enough free time yet. I think it could still be pickle-like if the load and dump functions had a `dset` attribute, e.g:

    ...
    hkl.dump(d1, 'filename.hdf')
    hkl.dump(d2, 'filename.hdf', dset='data_2')  

    d1 = hkl.load('filename.hdf')
    d2 = hkl.load('filename.hdf', dset='data_2')

I'd need to more formally define a data model for hickle files before embarking on this. I'm adding it to my todo list, but can't guarantee any progress at the moment. For now, it might be better to grab what you need from the code, or fall back to `h5py`, where there's an explicit `create_dataset` function.

**Comment by telegraphic** [comment]
Opening a new issue for the multi-read/write enhancement
