### ISSUE TITLE
Dumping / loading multiple hickles to a single HDF5 file

### ISSUE THREAD

**Issue by telegraphic** [telegraphic/hickle#21]
A desired enhancement, as discussed in issue https://github.com/telegraphic/hickle/issues/20.

Example usage:
```python
...
hkl.dump(d1, 'filename.hdf')
hkl.dump(d2, 'filename.hdf', dset='data_2')  

d1 = hkl.load('filename.hdf')
d2 = hkl.load('filename.hdf', dset='data_2')
```

I'm already calling it the "pickle jar"

**Comment by mmckerns** [comment]
If I wade into this before you, and it looks like something better serving here as opposed to stuck within `klepto`, I'll PR you..

**Comment by telegraphic** [comment]
Can now dump multiple hickles into one file:

    dump(a, "test.hkl", path="/test", mode="w")
    dump(a, "test.hkl", path="/test2", mode="r+")
    dump(a, "test.hkl", path="/test3", mode="r+")
    dump(a, "test.hkl", path="/test4", mode="r+")

    a = load("test.hkl", path="/test")
    b = load("test.hkl", path="/test2")
    c = load("test.hkl", path="/test3")
    d = load("test.hkl", path="/test4")

**Comment by hma02** [comment]
I'm a little confused about the mode option. I know for opening a file in python provides a read-only option like:
`
with open('x.txt', 'rb') as f:
    data = f.read()
`
But here the file is loaded without any option. Does it mean the file will be loaded with whichever mode it was dumped?

Thanks

**Comment by telegraphic** [comment]
Hi @hma02 , 

When loading the file, it opens it as read only, reads the data, then closes the file.

Mode is only really important when dumping the file. Hickle defaults to use `mode='w'` when dumping a file, which will overwrite any previous file. If you want to write multiple things to the same file, you necessarily have to open the file with `mode='r+'` though.
