### ISSUE TITLE
File Cache increasing

### ISSUE THREAD

**Issue by hma02** [telegraphic/hickle#22]
Is there any way to stop caching the file into memory while loading them?
I'm using hickle format to store large amount of image batches. When I run my python code on linux,checking the "top", the cache and "used mem" kept increasing until full. However I don't really need to cache them because I only use each file content once. So I wonder if this kind of feature can be disabled.

**Comment by telegraphic** [comment]
If you have large files and you don't want to load them into memory straight away, you can use `load_large`, which will return a `h5py` object instead (then you read it as you would with `h5py`).

If you are keeping references to objects after loading them, they will stick around. For example, if your code is doing something like

```
a = hkl.load('test1.hkl')
do_stuff(a)
b = hkl.load('test2.hkl')
do_stuff(b)
c = hkl.load('test3.hkl')
do_stuff(c)
...
```
You'll have three things sticking around. But if you do:

```
a = hkl.load('test1.hkl')
do_stuff(a)
a = hkl.load('test2.hkl')
do_stuff(a)
a = hkl.load('test3.hkl')
do_stuff(a)
```
Then you shouldn't see memory increase too much. You could also try [explicitly freeing memory](http://stackoverflow.com/questions/1316767/how-can-i-explicitly-free-memory-in-python), with `del` or `gc.collect()` but it's generally frowned upon and not particularly effective by the looks of it.

If you're already aware of all that, and you think there's a memory leak or issue, please post some example code that shows when the memory runaway happens, so we can track down exactly what's happening.

**Comment by hma02** [comment]
Sorry. Never mind. I tested again, and the cache increased to 33G and became stable at that level since then. I found that the cache increase may not be due to using hkl.load(), but it is due to caching the file content. I guess the Linux OS is doing something under the hood (perhaps with some algorithms as well) to control whether it needs to cache the file or not. Thanks.
