### ISSUE TITLE
Should be able to handle recursive tuples of tuples of numpy objects

### ISSUE THREAD

**Issue by sdh4** [telegraphic/hickle#24]
hickle is not capable of handling nested structures of lists and tuples containing various leaf nodes of numpy arrays, integers, strings, etc. at various positions.

This is because internally its handling of lists and tuples is not recursive.  If dump_list() used the same dumper_lookup() logic to dump the elements of the list as the main dump() function, then hickle would be able to handle arbitrarily deep structures. Same applies to dump_tuple() and dump_dict(). 

Since hdf5 natively handles tree structured (or graph-structured) data, all of this can be made to work just fine. 

This would also dramatically simplify dump_dict()

**Comment by sdh4** [comment]
Here (attached) is a first-cut patch against 1.4.0 for adding recursive list/tuple support.

It works with recursive tuples and lists, but I haven't tackled dicts yet. 

[recursivepatch.txt](https://github.com/telegraphic/hickle/files/52871/recursivepatch.txt)

**Comment by telegraphic** [comment]
@sdh4 something like this has been on my todo list for "hickle v2" for quite a while, so thanks for tackling it.

Applying the patch and running the unit tests, it's failing for me in

```
def test_list():
    """ Dumping and loading a list """
    filename, mode = 'test.h5', 'w'
    list_obj = [1, 2, 3, 4, 5]
    dump(list_obj, filename, mode)
    list_hkl = load(filename)
    #print "Initial list:   %s"%list_obj
    #print "Unhickled data: %s"%list_hkl
    try:
        assert type(list_obj) == type(list_hkl) == list
        assert list_obj == list_hkl
        
        os.remove(filename)
    except AssertionError:
        print "ERR:", list_obj, list_hkl
        import h5py
        a = h5py.File(filename)
        print a.keys()
        print a['data'].keys()
        os.remove(filename)
        raise
```
output is

```
ERR: [1, 2, 3, 4, 5] [None, None, None, None, None]
[u'data', u'type']
[u'0', u'1', u'2', u'3', u'4']
```
it appears to be making groups "1", "2", "3", "4", "5" instead of a dataset. The case where the list (or more generally an iterable) is a simple list of numbers probably needs to be treated differently to a heterogeneous mix of random things? I don't know the best way to tackle that...

**Comment by sdh4** [comment]
The solution to the immediate bug in my patch is to add dumpers/loaders for Python's native integer/floating point types. (Actually, since the routines are essentially the same as the np_dtype routines the functionality could just be wrapped in to those)i
```
def dump_python_dtype(obj, h5f, **kwargs):
    """ dumps a python dtype object to h5py file"""
    h5f.create_dataset('data', data=obj)
    h5f.create_dataset('type', data=['python_dtype'])

def load_python_dtype(arr):
    """ Load a numpy array """
    # Just return first value                                                   
    return arr.value
```

add to dumper_lookup.types{}: 
```
        int: dump_python_dtype,
        float: dump_python_dtype,
        long: dump_python_dtype,
```
add to load_stuff.types{}: 
```
                'python_dtype': load_python_dtype
```

**Comment by sdh4** [comment]
I would do an initial check on each list to determine if all elements are (a) the same type, and (b) a fundamental type, and if so store it as a single dataset. Kind of along the same lines of the old list-of-numpy-arrays check (no longer necessary with this patch).

**Comment by sdh4** [comment]
One minor bug I notice in the above fix is that if you hickle a Python 'long' you end up with an 'int' when unhickling. I think this is because it is relying on hdf5 to store and restore the type, and I don't think h5py distinguishes between python 'int' and 'long'.... solution is probably to explicitly store the name of the type as well, and then do an explicit cast on load.

**Comment by sdh4** [comment]
Another related fix: in load_np_list(), 
change the iteration over group.keys to: 
```
   for key in sorted(group.keys(),key = lambda key: int(key)):
```
This way if the number of keys exceeds nine, the sort will be done as a numeric sort and the list/tuple elements will be in their correct order. Otherwise it does an alphabetical sort leading to the wrong order
(this fix applies regardless of my patch above)

**Comment by telegraphic** [comment]
Hey, I've opened a 'dev' branch for this, as it might break backwards compatibility. This might be a good time to also do some changes toward v2.0 (see #11)

**Comment by craffel** [comment]
Not sure if this is related or a separate issue, but hickling a tuple or list or dict of lists of numpy arrays fails, e.g.:

```
>>> hickle.dump([[np.array([10., 20.]), np.array([10, 20, 30])], [np.array([10, 2]), np.array([1.])]], 'test.h5')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4643250fb405> in <module>()
----> 1 hickle.dump([[np.array([10., 20.]), np.array([10, 20, 30])], [np.array([10, 2]), np.array([1.])]], 'test.h5')

/usr/local/lib/python2.7/dist-packages/hickle.pyc in dump(obj, file, mode, track_times, **kwargs)
    374         # Open the file
    375         h5f = file_opener(file, mode, track_times)
--> 376         dumper(obj, h5f, **kwargs)
    377         h5f.close()
    378     except NoMatchError:

/usr/local/lib/python2.7/dist-packages/hickle.pyc in dump_list(obj, h5f, **kwargs)
    171         _dump_list_np(obj, h5f, **kwargs)
    172     else:
--> 173         h5f.create_dataset('data', data=obj, **kwargs)
    174         h5f.create_dataset('type', data=['list'])
    175

/usr/local/lib/python2.7/dist-packages/hickle.pyc in create_dataset(self, *args, **kwargs)
     98     def create_dataset(self, *args, **kwargs):
     99         kwargs['track_times'] = getattr(self, 'track_times', True)
--> 100         return super(H5FileWrapper, self).create_dataset(*args, **kwargs)
    101
    102     def create_group(self, *args, **kwargs):

/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.pyc in create_dataset(self, name, shape, dtype, data, **kwds)
    101         """
    102         with phil:
--> 103             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    104             dset = dataset.Dataset(dsid)
    105             if name is not None:

/usr/local/lib/python2.7/dist-packages/h5py/_hl/dataset.pyc in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     85         else:
     86             dtype = numpy.dtype(dtype)
---> 87         tid = h5t.py_create(dtype, logical=1)
     88
     89     # Legacy

h5py/h5t.pyx in h5py.h5t.py_create (/tmp/pip-build-aCD9_n/h5py/h5py/h5t.c:15500)()

h5py/h5t.pyx in h5py.h5t.py_create (/tmp/pip-build-aCD9_n/h5py/h5py/h5t.c:15331)()

h5py/h5t.pyx in h5py.h5t.py_create (/tmp/pip-build-aCD9_n/h5py/h5py/h5t.c:15249)()

TypeError: Object dtype dtype('O') has no native HDF5 equivalent
```

**Comment by telegraphic** [comment]
Ok, just made a big refactor of the code, and it should now preserve list order #26 and handle recursive structures. I'm going to close this for now, but reopen if anyone find that it fails in some situations.
