### ISSUE TITLE
Using dump is there anyway to not output the individual dataset names?

### ISSUE THREAD

**Issue by cosmojellyfish** [telegraphic/hickle#25]
Hello hickle creators,

This is a wonderful package and I want to say thank you for putting it together! It works like a breeze.

As a test, I followed your example in the readme file. I extended to get closer to the example I need for outputting my own dataset.

h = 22
data = {
    
    "single_eff_N_{0}".format(h) : np.array((100)),
    "single_L_PSD_{0}".format(h) : np.array((100,1000))
        }
        
hkl.dump(data, 'output_filename2.h5')

When I look into the file that I created, it has additional information that I would prefer not to have. It wasn't quite clear to me by looking at the source code for hickle how this piece of information gets written down. I am still learning the ins-n-outs of store data into hdf5 files and am not sure where to look to ask it not to output that info. The datasets that I would like to use this on are pretty long and it would be great not to have the redundancy. 

![additional info](https://cloud.githubusercontent.com/assets/7946375/11671799/5ad4dc94-9dd0-11e5-809d-99f41e27efef.png)

Thank you!

**Comment by telegraphic** [comment]
Hey @cosmojellyfish 

Glad to hear you're enjoying hickle! If you're getting in deep to HDF5 and actually looking at the file internals, it might be worth getting familiar with `h5py`, which is what `hickle` is built upon. That'll give a lot more flexibility, but won't have the simple pickle-like load and dump functionality that is the sole reason for hickle existing.

For `hickle`, those metadata objects are required so that data dumped with `dump()` will load with the `load()` function. In a future (non backward-compatible) version of hickle, I'll move the _data etc from datasets to attributes, which is a nicer way of storing metadata. That said, the python-centric metadata is required by hickle, so while I can move it to HDF5 attributes, it'll still be there...

**Comment by cosmojellyfish** [comment]
Thanks for getting back to me so quickly!

Yes, I was definitely looking for a simple pickle-like load and dump. I was hoping there would be a simple way to write my dictionaries and numpy arrays right into h5py. Once I stumbled on this I was really excited. I found this through a stackoverflow forum which is great.

It is helpful to know that the reason you have the _data is for the load() function. It would be WONDERFUL in the future to have all the metadata in a separate place. I have gigantic piles of dictionaries and numpyarrays and that would really help the cleanliness for my h5 files with others who aren't quite hip to hickle yet.

Looking forward to that update!

**Comment by telegraphic** [comment]
Ok, I've made some changes on the dev branch:
https://github.com/telegraphic/hickle/tree/origin/dev

It was pretty straightforward, and all the tests seem to be passing. Can I please get you to have a look and see if it's doing what you want it to?

**Comment by cosmojellyfish** [comment]
Hey telegraphic,

Thanks for the fix!

I tested hicklev2 and it does store the files nicely without all the additional information.

Reading the data in using  h5py.File works normally. 

I just need to wrap the the dataset with a numpy array and keep on trucking.

hkl.load does not work as you said it would not though this particular piece of it affect me as much

It does store a weird little A on each group or dataset which I am just showing you is a thing.

![weird little a](https://cloud.githubusercontent.com/assets/7946375/11695193/8ce7f858-9e73-11e5-8a55-e28319891a94.png)

I'll let you know as I keep working with it how it all goes.

Thanks again!

**Comment by ZedThree** [comment]
@cosmojellyfish That little 'A' lets you know that the dataset has attributes attached to it - the hickle metadata, in this case.
