### ISSUE TITLE
Unable to dump complex values using a dictionary

### ISSUE THREAD

**Issue by jbuencuerpo** [telegraphic/hickle#29]
I am trying to dump a dictionary with some complex values in a dictionary, I get a warning:

_UserWarning: <type 'complex'> type not understood, data have been serialized_

However for the same data I have numpy arrays with complex data in them, and are pickle without problem. It this expected, I am doing something wrong?
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import hickle as hkl
import numpy as np
data = {"A":1.5, "B":1.5 + 1j, "C":np.linspace(0,1,4) + 2j}
hkl.dump(data, "foo.hkl")
#/home/user/.local/lib/python2.7/site-packages/hickle.py:497: UserWarning: <type 'complex'> type not understood, data have been serialized
data_load = hkl.load("foo.hkl")
print data_load["B"]
# ['c__builtin__\ncomplex\np1\n(F1.5\nF1\ntRp2\n.']
print data_load["C"]
# [ 0.00000000+2.j  0.33333333+2.j  0.66666667+2.j  1.00000000+2.j]
```

 Cheers,

**Comment by telegraphic** [comment]
Thanks for spotting this. The complex python data type should now be supported; I've also added a unit test and added a line for handling complex data.
