### ISSUE TITLE
Not able to load hickle

### ISSUE THREAD

**Issue by dlmacedo** [telegraphic/hickle#30]
Dear friends,

I am having the following error when trying to import hickle:

```
>>> import hickle as hkl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dlm/theano/lib/python3.4/site-packages/hickle.py", line 621
    print h_node.name, py_type, h_node.attrs.keys()
               ^

```
Can you help me?

Thanks,

David

**Comment by telegraphic** [comment]
Hi David,


Hickle is not currently compatible with Python 3. This is on the roadmap, but currently in the too-hard basket. I’m getting more Py3 requests so I’ll try and prioritize this. Think months not days though :/


- Danny

**Comment by telegraphic** [comment]
Merging with https://github.com/telegraphic/hickle/issues/8
