### ISSUE TITLE
Hickle fails with dictionaries with unicode keys

### ISSUE THREAD

**Issue by migel** [telegraphic/hickle#36]
hickle 2.1.0 on python 2.7:

`str` keys ok:

``` python
In [10]: data = {'abc': 123, 'def': 456}
In [12]: hickle.dump(data, 'tst.hkl')
In [13]: data2 = hickle.load('tst.hkl')
In [14]: data2
Out[14]: {'abc': 123, 'def': 456}
```

`unicode` key fail:

``` python
In [15]: data = {'abc': 123, u'def': 456}
In [16]: hickle.dump(data, 'tst.hkl')
In [17]: data2 = hickle.load('tst.hkl')
In [18]: data2
Out[18]: ['abc', u'def']
```

**Comment by telegraphic** [comment]
Ugh, interesting edge case. It looks like `data = {u'abc': 123, u'def': 456}` works, but returns keys as strings not unicode.

**Comment by avierck** [comment]
I guess one of the culprits here is check_iterable_item_type( ), which only dumps a dict if all of its items are of the same type - is this something to be expected of a dict?

**Comment by telegraphic** [comment]
I guess not - you can use almost any hashable type as a key (there's some interesting reading on https://wiki.python.org/moin/DictionaryKeys about this). The same failure would happen for e.g. {0 : 'test', 'key' : 'test'}

I think you're right that it's `check_iterable_item_type( )` causing the bug. This function is required for hierarchical / recursive mapping to HDF5, but clearly needs some fine tuning.

**Comment by telegraphic** [comment]
Fix was committed in Jan, and no further discussion in the last few months, so closing this thread.
