### ISSUE TITLE
User-defined object handling 

### ISSUE THREAD

**Issue by jremmons** [telegraphic/hickle#39]
I'm trying to dump a user-defined object to a hickle file then later load it. However, when I try to load the object it is being deserialized as a numpy array instead of the user-defined python object. Below is an example...

```
import hickle

class Test:
    def __init__(self, _x, _y):
        self.x = _x
        self.y = _y

with open('bar.hkl', 'w') as f:
    obj = Test('hello', 'world')
    hickle.dump(obj, f)

with open('bar.hkl', 'r') as f:
    obj = hickle.load( f )

    print 'data type:', obj.dtype
    print obj
    print obj.x
    print obj.y
```

The output when this is run in python2.7.12 is...
```
>$ python test.py
/usr/local/lib/python2.7/dist-packages/hickle.py:498: UserWarning: <type 'instance'> type not understood, data have been serialized
  "serialized" % type(py_obj))
(u'/data_0', 'pickle', [u'type'])
data type: |S62
["(i__main__\nTest\np1\n(dp2\nS'y'\nS'world'\np3\nsS'x'\nS'hello'\np4\nsb."]
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    print obj.x
AttributeError: 'numpy.ndarray' object has no attribute 'x'
```

**Comment by telegraphic** [comment]
Hey @jremmons, looks like something might be amiss with unpickling serialized objects, I'll keep this open and look into it when I can. 

FWIW, I've been working on making it easier to add new objects on the `dev` branch, which also adds some basic support for python3.  Haven't had time to work on this much in the last few weeks. The general idea is that there is a loaders/ directory into which new types of object to store can be added.

**Comment by jremmons** [comment]
I think I found an easy fix for the code on master, but I realized that the dev code does things very differently (ignore the pull request I made). If I have time I might try to fix this myself!

**Comment by mmckerns** [comment]
I added the ability to store these objects in `hickle` in #19.  The functionality was removed in #23.

**Comment by telegraphic** [comment]
Hi @mmckerns -- troubling that the functionality was removed, thanks for digging down and finding where, that answers my "something's amiss". We'll need to add in a test to make sure that if someone breaks this functionality in the future they get shouted at by Travis-CI.

**Comment by mmckerns** [comment]
Ok, so that answers if it was done on purpose.  It's a simple patch to put the functionality back in, or at least it was when I added it... I haven't seen if there are any changes that might be blockers recently.  What do you want to do about it?  I can PR them back in... unless you'd rather do it.

**Comment by telegraphic** [comment]
@mmckerns if you wouldn't mind doing this on the master branch (should still be straightforward), I'll add this to the dev branch when I get a chance (I need to think about Py2 and Py3 compabiliity for this branch).

**Comment by mmckerns** [comment]
I submitted the changes.  There should probably be some tests created showing using hickle on complex and user-defined objects.
