### ISSUE TITLE
ShimWarning when importing hickle in ipython

### ISSUE THREAD

**Issue by sjlee1980** [telegraphic/hickle#42]
Hello,

I'm using hickle 2.1.0, python 2.7.11, ipython 5.3.0.

`import hickle`

still allows me to use hickle, but the warning message below is bothering:

/Users/xxx/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)

Thanks

**Comment by telegraphic** [comment]
Hi @sjlee1980 , I have no idea what this means, but hickle doesn't have any dependencies on ipython so I'd bet this has to be something to do with numpy or h5py. Can you try these lines one by one:

```
import os
import numpy as np
import h5py as h5
import re
```

And see if any create a shimwarning?

**Comment by telegraphic** [comment]
Closing as issue appears to be non-hickle
