### ISSUE TITLE
global name 'scipy' is not defined

### ISSUE THREAD

**Issue by mohawkjohn** [telegraphic/hickle#43]
This is a really frustrating error to get after running a couple hours of processing and trying to dump a file:

```
Traceback (most recent call last):
  File "__init__.py", line 28, in <module>
    dof    = 6)
  File "/home/mohawkjohn/axiom_control/plot.py", line 198, in all
    cogs_6dof = cog.compute_or_load_candidates(thruster_config, R = R, F = F, dof = 6, n_on = 6)
  File "/home/mohawkjohn/axiom_control/cog.py", line 244, in compute_or_load_candidates
    hkl.dump(cogs, filename, 'w')
  File "/home/mohawkjohn/.local/lib/python2.7/site-packages/hickle.py", line 319, in dump
    _dump(py_obj, h_root_group, **kwargs)
  File "/home/mohawkjohn/.local/lib/python2.7/site-packages/hickle.py", line 259, in _dump
    elif check_is_scipy_sparse_array(py_obj):
  File "/home/mohawkjohn/.local/lib/python2.7/site-packages/hickle.py", line 237, in check_is_scipy_sparse_array
    is_sparse = type(py_obj) in (type(scipy.sparse.csr_matrix([0])), type(scipy.sparse.csc_matrix([0])))
NameError: global name 'scipy' is not defined
```

I'm trying to write a NumPy ndarray. I don't have SciPy installed. I don't *need* SciPy. SciPy is not a dependency for Hickle. I now have to install SciPy to allow it to do a simple type-check.

:P

**Comment by telegraphic** [comment]
Hi @mohawkjohn ,  I can see that would be frustrating. I have for now added scipy as a dependency in the master branch of hickle.

Note that I have switched to work mainly on my [dev branch](https://github.com/telegraphic/hickle/tree/dev), which is a pretty significant refactor. One of the aims of this branch is to make `numpy` and `scipy` optional dependencies, add support for Python3, and add support for objects and types from other commonly used packages (e.g. `pandas` and `astropy`). For now, the dev branch needs beta testers so is 'at your own risk'.

**Comment by telegraphic** [comment]
Ok, the travis-ci tests on the dev branch are passing without scipy, and the master branch has added it as a required dependency in setup.py, so I'm calling this one closed.
