### ISSUE TITLE
Redundant data_0?

### ISSUE THREAD

**Issue by vadimkantorov** [telegraphic/hickle#44]
Is it possible to make hickle to strip `data_0` for simple structures like below?

```python
import hickle
hickle.dump(dict(a = 1, b = dict(c = 2)), 'log.h5')
```
```shell
h5ls -r log.h5

# /                        Group
# /data_0                  Group
# /data_0/a                Group
# /data_0/a/data_0         Dataset {SCALAR}
# /data_0/b                Group
# /data_0/b/data_0         Group
# /data_0/b/data_0/c       Group
# /data_0/b/data_0/c/data_0 Dataset {SCALAR}
```

Is there any reason for having `data_0` in the group structure? Couldn't the object be represented like below? (which is nicer for manual inspection)
```
# /                 Group
# /a                Dataset {SCALAR}
# /b                Group
# /b/c              Dataset {SCALAR}
```

Thanks for the useful package! It's quite handy for serializing PyTorch neural net models to a portable format.

**Comment by telegraphic** [comment]
Hey @vadimkantorov , totally agree that the _0 is ugly. HDF5 datasets are unordered, and for dictionaries of dictionaries, the numbers are indeed unnecessary. The numbers are added to preserve the order of lists, sets, tuples, e.g.:

```
a = [
  np.array([1,2,3]),
  np.array([3,4,5])
]

hickle.dump(a, 'test.hkl')
```

Which to store in HDF5, the arrays are assigned to datasets `data_0` and `data_1`. 

I can definitely look into removing the _0 if there is only one item for hickle v3 (on the dev branch), and am putting it on the todo list. For hickle v2, we unfortunately can't make structural changes as it would mean the file wouldn't load in old versions of the code and old files wouldn't load in the new version of the code.

**Comment by vadimkantorov** [comment]
Thanks! That would be great!
