### ISSUE TITLE
How to append?

### ISSUE THREAD

**Issue by MichaelXin** [telegraphic/hickle#45]
`import hickle

import numpy as np

a = np.ones(32000, dtype='float32')

hickle.dump(a, 'test.hkl', mode='a')

b = np.ones(32000, dtype='float32')

hickle.dump(b, 'test.hkl', mode='a')
`

Then I got an error: Unable to create link (Name already exists)

**Comment by telegraphic** [comment]
Hi @MichaelXin , unfortunately HDF5 files are not designed for append operations. If you want to store multiple things in one file you can do:

```python
import hickle as hkl
import numpy as np

a = np.ones(32000, dtype='float32')
b = np.ones(32000, dtype='float32') * 2

hkl.dump(a, 'test.hkl', path='a_data')
hkl.dump(b, 'test.hkl', path='b_data')

aa = hkl.load('test.hkl', path='a_data')
bb = hkl.load('test.hkl', path='b_data')
```

**Comment by ZedThree** [comment]
Hi @telegraphic, I'm a bit confused by your answer. It's definitely possible to append to an HDF5 dataset (see [this SO answer](https://stackoverflow.com/a/16215898/2043465)), but it would require hickle to create all datasets with an unlimited dimension which could complicate matters.

**Comment by telegraphic** [comment]
Hi @ZedThree, perhaps we are talking semantics but I would call that a resize, not an append operation. But certainly yes, you are correct that for all intents and purposes you can get data to be appended to an existing dataset, provided you setup your dataset correctly. 

FWIW, the `maxshape` keyword should automatically pass on to the `h5py.create_dataset` call if added to the `hickle.dump` command, but actually implementing an append through hickle would be pretty nasty so I'm going to steer clear for now (but pull requests welcome)! If append functionality is a key requirement, then I'd suggest either using PyTables or using a simpler file type.

**Comment by mpanighel** [comment]
Hi @telegraphic, great package!

Just a note, for the append to work any additional `dump` should have `mode='a'`, otherwise the file is overwritten:
```
hkl.dump(b, 'test.hkl', path='b_data', mode='a')
```

**Comment by 1313e** [comment]
Also, keep in mind that with the changes I made to `hickle` in #94, one can also pass an open HDF5-file to `hickle`:
```
with h5py.File('test.hkl', 'w') as file:
    file.attrs['type'] = "This is a Hickle file"
    hickle.dump(a, file, path='a_data')
    hickle.dump(b, file, path='b_data')
```
This means that one can also use it on already existing HDF5-files (by obviously using `'r+'/'a'` instead of `'w'` as the mode), or easily mix hickled datasets with normal datasets.

**Comment by 1313e** [comment]
As data objects can now be hickled and added to already existing HDF5-files (open or not), and to groups as well, I am going to close this issue.

Making datasets resizable would require a lot more knowledge beforehand to make that happen.
There are many different ways in which the user could easily mess up the HDF5-file, which added unnecessary complexity, given that `hickle` is meant to be used for archival storage.
