### ISSUE TITLE
hickle complex object.

### ISSUE THREAD

**Issue by Fish-Soup** [telegraphic/hickle#49]
Hi its unclear to me if this can be used to save complex objects into memory, including methods and imported modules? Or is it just for simple data formats.

Many thanks

**Comment by telegraphic** [comment]
Hey @Fish-Soup -- my usage of hickle is indeed for writing scientific data structures to file, with the intent that others may be able to read the data with or without the hickle module, and/or in other programming languages and environments. 

However, objects that have no obvious underlying data may be serialized and written to hickle files too.

**Comment by telegraphic** [comment]
Closing this, addressed in #51
