### ISSUE TITLE
Incorrect data type stored - ndarray instead of float

### ISSUE THREAD

**Issue by vladbph** [telegraphic/hickle#50]
Original object:
	(('6', **0.0, 279.0**, ('', 'data', 'probe_td', 'eval', '00000043', 's02_2011_11_03', '00000043_s02_a02.edf')),
	[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ...])

Stored object:
	(('6', **ndarray,ndarray**, ('', 'data', 'probe_td', 'eval', '00000043', 's02_2011_11_03', '00000043_s02_a02.edf')),
	[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ...])

**Comment by telegraphic** [comment]
Hey @vladbph, yuck :/. Could you please confirm what version of hickle you are using (type `pip freeze` if you installed via pip and it'll show you). If you installed from github, did you use the`master` or the `dev` branch?

**Comment by vladbph** [comment]
Hi,
I installed with pip... It is 2.1.0

**Comment by peendebak** [comment]
@telegraphic I have the same issue. A minimal example:
``` python
import hickle
import numpy as np

fid='test.h5py'
r0={'test':  np.float64(10.) }
s=hickle.dump(r0, fid)
r=hickle.load(fid)
print(r)

print(type(r0['test']))
print(type(r['test']))
```
results in
```
{'test': array(10.0)}
<class 'numpy.float64'>
<class 'numpy.ndarray'>
```
I am using the dev version of hickle.

**Comment by telegraphic** [comment]
Thanks @vladbph and @peendebak. I've just pushed a commit to address this on the dev branch!

**Comment by telegraphic** [comment]
Think this is resolved, so closing issue.
