### ISSUE TITLE
Python3: legacy loading

### ISSUE THREAD

**Issue by jan-janssen** [telegraphic/hickle#55]
Hi, 

I tested the hickle code and found that the part in line 487 (dev branch): 
` ` `        
except AssertionError:
            import hickle_legacy
            return hickle_legacy.load(fileobj, safe)
`` ` 
is not Python3 compatible, maybe it is reasonable to implement a `_legacy_load()` function instead. 

Best regards 

Jan

**Comment by telegraphic** [comment]
Thanks @jan-janssen, agreed that would be a reasonable approach and current setup is bad.

**Comment by telegraphic** [comment]
Think this is fixed so closing issue.
