### ISSUE TITLE
hickle is broken, at least in python3

### ISSUE THREAD

**Issue by gioelelm** [telegraphic/hickle#56]
If I run the example in the tutorial I get the following error.
I am referring to the version installed using pip

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-76-16caf8e6745e> in <module>()
      7 
      8 # Dump to file
----> 9 hkl.dump(array_obj, 'test.hkl', mode='w')
     10 
     11 # Dump data, with compression

~/anaconda3/lib/python3.6/site-packages/hickle.py in dump(py_obj, file_obj, mode, track_times, path, **kwargs)
    306     try:
    307         # Open the file
--> 308         h5f = file_opener(file_obj, mode, track_times)
    309         h5f.attrs["CLASS"] = 'hickle'
    310         h5f.attrs["VERSION"] = 3

~/anaconda3/lib/python3.6/site-packages/hickle.py in file_opener(f, mode, track_times)
    146     """
    147     # Were we handed a file object or just a file name string?
--> 148     if isinstance(f, file):
    149         filename, mode = f.name, f.mode
    150         f.close()

NameError: name 'file' is not defined
```

**Comment by telegraphic** [comment]
Hi @gioelelm -- the version installed by pip is the 'stable' version, which is Python 2 only. If you'd like to use Python 3 please check out the [dev branch](https://github.com/telegraphic/hickle/tree/dev). I need a big chunk of time to test legacy and backwards compatibility before I pull in the changes from the dev branch into the stable (pip) version.

Unfortunately, pip does not (to my knowledge) have any way to check if a package works in Py2 or Py3, so in the interim it is hard to stop people running into this :/.
