### ISSUE TITLE
hickle only compatible with python 3.6

### ISSUE THREAD

**Issue by peendebak** [telegraphic/hickle#59]
In particular: ModuleNotFoundError is new in python 3.6 and used in https://github.com/telegraphic/hickle/blob/dev/hickle/loaders/load_python3.py  (around line 109).

**Comment by telegraphic** [comment]
I think this is now fixed? I've also added Travis-CI tests for more Py 3 versions.

**Comment by peendebak** [comment]
Looks good to me
