### ISSUE TITLE
saving list with string fails

### ISSUE THREAD

**Issue by peendebak** [telegraphic/hickle#62]
The following minimal example fails on the  `dev` branch.
```
import hickle

hickle.dump('hi', 'test1.hickle') # fine
hickle.dump(['hello'], 'test2.hickle')  # fails 
```
It is related to the `h5py` string handling, but since the data is so simple I think hickle should be able to handle this case.

@telegraphic

**Comment by telegraphic** [comment]
Ugh, that's a bad one. Looks like this passes in Py2 but not Py3.

**Comment by telegraphic** [comment]
the underlying issue is that h5py doesn't like the Py3 `str`. For example. this fails:

```
import h5py
h = h5py.File('test.hkl')
h.create_dataset('data', data=['hello'])
```
I've added a patch that should fix this, but it currently will return `[b'hello']`. Need to think of a neat way to catch this edge case. Interestingly, mixed lists e.g. `[1, 2, 'a', 'b']` were already working as they're stored differently internally.

**Comment by peendebak** [comment]
@telegraphic The patch works, but the results are a little bit confusing
```
import hickle

hickle.dump('hi', 'test1.hickle') # fine
v=hickle.load('test1.hickle')
print(type(v) )

hickle.dump(u'hi', 'test1.hickle') # fine, but a str is returned
v=hickle.load('test1.hickle')
print(type(v) ) # str?

hickle.dump(['hello'], 'test2.hickle')  # works, but a bytes object is returned in the list
v=hickle.load('test2.hickle')
print(type(v) )
print(type(v[0]) ) # a bytes object?
```
Is it an option to make storing and loading results consistent by adding some metadata to the hdf5 file for each `bytes` and `str` object?

**Comment by telegraphic** [comment]
@peendebak I think adding extra metadata is the only way 😢 . I think this issue should be fixed, and then that's a good time to merge the dev branch into master (see #8).

**Comment by peendebak** [comment]
@telegraphic Ok, do you want to make a first PR with the metadata for the strings? I am willing to make one, but you are much more familiar with the hickle codebase.

**Comment by telegraphic** [comment]
@peendebak this was pretty painful, and my fix is a little ugly, but I think the latest push should fix it?

**Comment by peendebak** [comment]
@telegraphic Patch indeed fixes the issue thanks!

Two things I noticed during testing:
- an `OrderedDict` is not recognized as an object and that the order of keys in a python `dict` is not preserved. Since python 3.6 the order of dict keys is preserved [3.6 new dict](https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation), although it is new yet in the specs. 
- the code handling `str` vs. `bytes` is coupled to the list -like structures (e.g. `list`, `tuple`, ...). for strings not in any of these we might encounter similar issues (although i have not yet found these)

**Comment by telegraphic** [comment]
@peendebak hooray! Re you points:

* I'd like to add support for objects in [Collections](https://docs.python.org/3/library/collections.html), including `OrderedDict` and `defaultdict`. I wasn't aware of that Py3.6 change to preserve order! This may actually need extra metadata in the HDF5 file to pull off.
* The code in question is actually only called for lists where all entries are of the same type, as in this case it saves it to a HDF5 dataset. If the list is mixed, e.g. `[1, 2, 'a', 'b']` then the data need to be saved in a HDF5 group containing several datasets. I *think* that code functions fine, as should non-list strings.

I'll close this issue for now and make a new one for `OrderedDict`.
