### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by PyPatel** [telegraphic/hickle#66]
import hickle as hkl
    a = 'full path to file'
    b = hkl.load(a,'r')
I am getting following error during another run. I don't know why it is creating `NoneType` type error. **h5py** with the `h5py.File(a)` is working.

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 624, in load
        py_container = _load(py_container, h_root_group)
      File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 756, in _load
        subdata = load_dataset(h_group)
      File "/usr/local/lib/python2.7/dist-packages/hickle.py", line 643, in load_dataset
        py_type = h_node.attrs["type"][0]
    AttributeError: 'NoneType' object has no attribute 'attrs'

I am able to read the file using `h5py`. This must be the hickle error.
How come `h_node` is producing `None`?

**Comment by PyPatel** [comment]
File have full permission access(7777) also.

**Comment by telegraphic** [comment]
Hi @PyPatel -- there is not quite enough information to debug this. From what I can tell, you are probably trying to open an older file with a newer version of hickle. Or, you're trying to open a file that is not a hickle file.

**Comment by PyPatel** [comment]
I created the Hickle file (`.hkl`) just in the previous step of the data processing. I created the file using `hickle.dump()`. I am using same hickle version for both `hickle.dump` and `hickle.load()` which is `Hickle 2.1.0`.   I had run the same commands on different data set in last few days. It worked fine. I don't know why it is showing errors now. 

**About the data:** It is hickle of `.jpg` images stitched together to give the input to the training model.

**Comment by telegraphic** [comment]
Thanks for the extra info, that does sound unusual. If you can create a minimal example that breaks it so I can reproduce the error, I'll have a go at fixing it. Having said that, you may be better off switching over to the [dev branch](https://github.com/telegraphic/hickle/tree/dev), which is more actively developed. That may just fix your error!

**Comment by PyPatel** [comment]
Here is the Data Processing code (which is generating hickle file) [Data Processing](https://gist.github.com/PyPatel/fb3b21e25ea332ea56155a696de8fc42)

After Generating this `X_train.hkl`, I am using `hkl.load('full/path/X_train.hkl, 'r')`

I have to mention that I am working on `docker container` through `SSH` on the server where I am **not** admin, but File generated have full access to everyone (which is done by `chmod 777`). Could this be another permission issue. (If it is, how is it working on h5py)

**Comment by PyPatel** [comment]
Okay. I am getting this Warning during the data processing. 
`UserWarning: <type 'numpy.string_'> type not understood, data have been serialized
  "serialized" % type(py_obj))`

**Comment by PyPatel** [comment]
The above warning is coming from line 34 of the code. `X_train.hkl` is giving the error.

**Comment by PyPatel** [comment]
I think the problem is at the `h_root_group`  on line 555 of `hickle.py`   Please have a look.

**Comment by PyPatel** [comment]
**Work around:** use `h_root_group = h5f.get('/')` in line 555 instead of `h_root_group = h5f.get(path)`
