### ISSUE TITLE
hickle.load() adhoc print outputs in Jupyter ..

### ISSUE THREAD

**Issue by anshoomehra** [telegraphic/hickle#75]
Hi There,

Awesome job with coding this utility!!

I am having weird behavior with **hickle.load()** in Jupyter, loading some files it prints the output of load, sometimes it does not print any output. Not able to find out any information on google search and hence logging the problem here..

Needless to say, I am trying to find out on how to stop printing every output, as huge files are crashing Jupyter. Is there a way to mute output ??

Example:

**cleaned_samples_for_trng = hickle.load("cleaned_samples_for_trng.hkl")**
b'string' ['ASR1001-X']
b'string' ['Data Assistance']
b"<class 'list'>" [b'asr1001' b'issues' b'atm' b'interface']
b'python_dtype' 472.0
b"<class 'list'>" [b'issues' b'atm' b'interface' b'want' b'verify' b'bug']
b'python_dtype' 2.0
b'python_dtype' nan

**ascii_cleaned_data = hickle.load('report_feb-may-2018_cleaned_col_rm.hkl')**
<No Output>

Both above files are something I created myself, they are pandas dataframes written to file with no compression, like below ..
**hickle.dump(ascii_cleaned_data, 'report_feb-may-2018_cleaned_col_rm.hkl')**

Appreciate any help!!

Thanks,
Anshoo

**Comment by telegraphic** [comment]
Hi @anshoomehra, thanks for picking this up. I traced this to a print() function that has now been removed. I've bumped to version 3.2.2 as this is a bugfix release

**Comment by anshoomehra** [comment]
@telegraphic Thank you so much, post upgrade to 3.2.2 it does resolve the issue :-)
