### ISSUE TITLE
Allow loading of hickle files between Py2 and Py3

### ISSUE THREAD

**Issue by srinadhu** [telegraphic/hickle#77]
When I try to load a hickle file, this is the error, what to do?

 hkl.load("sources_test.hkl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/hickle/hickle.py", line 515, in load
    raise RuntimeError("Cannot open file. This file was likely"
RuntimeError: Cannot open file. This file was likely created with Python 2 and an old hickle version.

**Comment by jclevesque** [comment]
Would be nice to have a solution that doesn't imply converting the hickle, which can be a hassle when they are large-ish.

**Comment by telegraphic** [comment]
@jclevesque and @srinadhu -- agreed that it would be nice to be have better inter-python compatibility. 

The main issue that has held this back is that Py2 and Py3 have incompatible types for strings (unicode, bytes, str), but I'd like to make hickle do a 'best effort' load, where it tries to load data and guess the best string type. 

Note: I've modified this issue a little bit and assigned it as an enhancement.

**Comment by 1313e** [comment]
As hickle is no longer compatible with Python 2, I feel like this is no longer a priority.
