### ISSUE TITLE
JoSS Review: Testing with `pytest`

### ISSUE THREAD

**Issue by betteridiot** [telegraphic/hickle#83]
I used `pytest` and the `pytest-coverage` plugin to run your automated tests. 

Initially `pytest` could not run your test suite. I needed to install `astropy` and `scipy` to get it to run. These are not in plain Python or Miniconda environments by default. Since your package did not specify them as requirements, the tests could not run.

I recommend adding them to your requirements.txt

**Comment by telegraphic** [comment]
Hi @betteridiot, this was the push I needed to figure out the ' square bracket install thing' (which I now know is called an 'extra optional dependency'). Not everyone will need/want astropy. Do you know if there's a good way to support this in unit testing?

**Comment by betteridiot** [comment]
Now that the tests are up and going. You should probably add a "Testing" section to your README.md to prompt users to run `python setup.py test` when installed from source.

**Comment by telegraphic** [comment]
Alrighty, I've added this to README.md

**Comment by telegraphic** [comment]
JOSS review is complete, closing this issue.
