### ISSUE TITLE
[FEATURE] Providing an open HDF5-file to dump/load does not close the file

### ISSUE THREAD

**Issue by 1313e** [telegraphic/hickle#92]
Something that may be useful is that when the user passes an open HDF5-file to the `hickle.dump` or `hickle.load` functions, they do not automatically close the HDF5-file afterwards.
Given that the user provided them as open, I think it would be pretty safe to assume that it will close the file itself.

Reason why I think this is useful is because I am hickling many objects to the exact same file, while I am controlling the paths within the file.
Currently, this means that the file is being opened and closed for every dump or load that I perform, while they are all executed after each other.
This is a bit stupid, as it creates both overhead and a lot of strain on the file system (obviously depending on how many times the file is opened and closed).

Doing this however would change the comment I made in #90 about using `with`-statements, as the  `h5f.close` should only be called if `hickle` opened the file itself (this can be done quite easily by using `finally`-clauses).
If you want, I can make the changes myself (including addressing the closing issue of #90) and simply create a PR.

**Comment by telegraphic** [comment]
I can definitely see the use case, happy to support the change. PR welcome! If timeline is not important, I'm happy to add this too, just not sure when my next maintenance session will be.

**Comment by 1313e** [comment]
Well, while I was looking throughout the code, I saw some quality of life issues that I would be more than happy to address.
So, I might as well do that while also implementing this change (if you do not mind of course).

**Comment by telegraphic** [comment]
Sure thing, always wonderful to have help! The code has evolved quite a lot since its first inception, and there was some complexity getting it to support both Py2 and Py3 -- there's certainly room for improvement on string handling.

Only note: if you do major whitespace changes please do a separate commit, so it's clear what the major changes are. (And you've probably noticed I deliberately don't follow PEP8 when it comes to lining up equal signs across lines).

**Comment by 1313e** [comment]
> Sure thing, always wonderful to have help! The code has evolved quite a lot since its first inception, and there was some complexity getting it to support both Py2 and Py3 -- there's certainly room for improvement on string handling.
> 
> Only note: if you do major whitespace changes please do a separate commit, so it's clear what the major changes are. (And you've probably noticed I deliberately don't follow PEP8 when it comes to lining up equal signs across lines).

Yes, I did notice that (about PEP8).
I was not going to make any changes to that.
More actually making some optimizations to getting Python2/Python3 compatibility.
I got quite a lot of experience with dealing with that problem while writing PRISM.

**Comment by 1313e** [comment]
@telegraphic Given that the `dev` branch is much behind the `master` branch, I will make a branch of `master` and work in that (after forking it obviously).
You will have to tell me what to do with the versioning then.

**Comment by telegraphic** [comment]
FWIW I've merged the changes on master back to dev. (For PRs from forks I don't mind commits directly to master branch as long as CI passes though)

**Comment by 1313e** [comment]
> FWIW I've merged the changes on master back to dev. (For PRs from forks I don't mind commits directly to master branch as long as CI passes though)

Oh, I have already made a branch based on `master`.
Guess we will see during the PR.

**Comment by telegraphic** [comment]
No worries

**Comment by 1313e** [comment]
Well, if you want, you can see some of the changes I have already made [here](https://github.com/1313e/hickle/tree/dev_1313e).

**Comment by 1313e** [comment]
@telegraphic Well, I am done.
Want me to create a PR from the `dev_1313e` branch into `master`?

I think I am going to take a look at the issue with dicts that I raised in #91.

**Comment by telegraphic** [comment]
@1313e sure thing, please go ahead!

**Comment by 1313e** [comment]
And this one can be closed now as well.
