### ISSUE TITLE
Slow Loading

### ISSUE THREAD

**Issue by catta202000** [telegraphic/hickle#96]
I did a loading speed test comparison between hickle and h5py.
I expected similar timings, but i found hickle to be 2-3x slower then h5py.

|compression| h5py  | hickle |
| ------------- | ------------- | ------------- |
|No Compression|0.0102|0.0237|
|gzip|0.2033|0.4078|
|lzf|0.0174|0.0423|

**Comment by catta202000** [comment]
This is the code i used:

```python
import numpy as np
import h5py
import hickle as hkl
import timeit

x = np.random.random((2000, 2000))
file=h5py.File('data.h5', 'w');file.create_dataset('x',data=x);file.close()
hkl.dump(x, 'data.hkl')
file=h5py.File('data_gzip.h5', 'w');file.create_dataset('x',data=x,compression='gzip');file.close()
hkl.dump(x, 'data_gzip.hkl', compression='gzip')
file=h5py.File('data_lzf.h5', 'w');file.create_dataset('x',data=x,compression='lzf');file.close()
hkl.dump(x, 'data_lzf.hkl',compression='lzf')

timeit.timeit("file=h5py.File('data.h5', 'r');x=file['x'][:];file.close()",
              setup="import numpy as np;import h5py", number=1000)/1000
timeit.timeit("x=hkl.load('data.hkl')",
              setup="import numpy as np; import hickle as hkl", number=1000)/1000
timeit.timeit("file=h5py.File('data_gzip.h5', 'r');x=file['x'][:];file.close()",
              setup="import numpy as np;import h5py", number=100)/100
timeit.timeit("x=hkl.load('data_gzip.hkl')",
              setup="import numpy as np; import hickle as hkl", number=100)/100
timeit.timeit("file=h5py.File('data_lzf.h5', 'r');x=file['x'][:];file.close()",
              setup="import numpy as np;import h5py", number=100)/100
timeit.timeit("x=hkl.load('data_lzf.hkl')",
              setup="import numpy as np; import hickle as hkl", number=100)/100
```

**Comment by telegraphic** [comment]
Hi @catta202000, if speed is your priority, and you're working predominantly with numpy arrays, it's definitely worth going direct with `h5py`. 

`hickle` uses `h5py` under the hood, so the difference in time is due to the extra checks and type conversions that `hickle` does. So, I would expect that the time difference to decrease as the array dimensions increase? 

To give some background on what I think is going on, if you create a file with hickle, but load it with h5py:

```python
import h5py
import hickle as hkl
import numpy as np

x = np.random.random((2000, 2000))
hkl.dump(x, 'data_lzf.hkl',compression='lzf')
h5 = h5py.File('data_lzf.hkl')
```

You can see extra attributes are attached (inspecting using ipython):

```python
In [7]: h5.attrs.items()
Out[7]:
[
  (u'CLASS', 'hickle'), 
  (u'VERSION', '3.3.3'), 
  (u'type', array(['hickle'], dtype='|S6')), 
  (u'PYTHON_VERSION', '2.7.14')
]

In [9]: h5['data_0'].attrs.items()
Out[9]:
[(u'type', array(['ndarray'], dtype='|S7'))]
```

Those attributes are used by hickle to check what the corresponding python type is, to reconstruct morepeculiar things like a `dict` consisting of `numpy` arrays and other python types. If you're working directly with numerical data, then the extra hickle attributes are indeed somewhat extraneous.

**Comment by telegraphic** [comment]
@catta202000 the timings do look a bit peculiar though, as I agree they look like `2x`, not  `x + overhead`. If you don't mind and are interested, could you please run tests on different sized arrays? E.g. `x = np.random.random((N, N))`, up to larger values of N, and see how the trend continues?

**Comment by 1313e** [comment]
I just tried this with `N=10000`, and I get `1.138s` for `hickle` and `0.375s` for `h5py`.

However, while I was doing that, I was observing my memory consumption and the memory usage for `hickle` was much higher (about two to three times higher) than it was for `h5py`.
What I think is happening, is that `hickle` is making copies of the data in the HDF5-file before actually converting it back, while `h5py` obviously does not (as it reads in data in a `np.ndarray` by default).
Making this copies can take a lot of time depending on how large they are.

**Comment by catta202000** [comment]
Increasing N, the times looks even worse:

N=2000

|compression| h5py  | hickle | ratio |
| ------------- | ------------- | ------------- | ------------- |
|No Compression|0.0102|0.0237|2.32x|
|gzip|0.2033|0.4078|2x|
|lzf|0.0174|0.0423|2.43x|

N=5000

|compression| h5py  | hickle | ratio |
| ------------- | ------------- | ------------- | ------------- |
|No Compression|0.1322|0.352|2.66x|
|gzip|1.3616|2.7799|2.04x|
|lzf|0.1773|0.4615|2.6x|


N=10000

|compression| h5py  | hickle | ratio |
| ------------- | ------------- | ------------- | ------------- |
|No Compression|0.5|1.4318|2.86x|
|gzip|5.4113|11.0315|2.03x|
|lzf|0.6917|1.8742|2.7x|

**Comment by telegraphic** [comment]
Interesting! Labelling as a bug for now, will need to run through code line by line to see what is tripping it up.

**Comment by 1313e** [comment]
I used to have this problem in my PRISM package as well, where I was making lots of unnecessary copies of NumPy arrays.
I simply introduced a new function called `np_array(*args, **kwargs)`, which returns `np.array(*args, copy=False, **kwargs)` and replaced every instance of `np.array` with `np_array` unless I explicitly required a copy (NumPy will still make a copy of an array, even with `copy=False`, if there is no way to avoid doing so).

**Comment by telegraphic** [comment]
OK, traced this to [hickle.py#557](https://github.com/telegraphic/hickle/blob/68b4c55c346057b18d537c646343f98b627b4ba3/hickle/hickle.py#L557), the `get_type_and_data` function actually loads the data, before it is re-loaded using the lookup. Fix will be changing to a `get_type` function that doesn't load data.

**Comment by telegraphic** [comment]
Ok, I think this should be fixed! I just pushed a v3.4.3. @catta202000 would you mind checking if that fixes the speed issue?

**Comment by catta202000** [comment]
Now the timing looks almost the same, thanks!

**Comment by telegraphic** [comment]
Thanks @catta202000, great find!
