### ISSUE TITLE
UserWarning : Hickle file is not Versioned

### ISSUE THREAD

**Issue by aditya-pandey221997** [telegraphic/hickle#99]
Hi,
I am trying to load hickle file in my python code. I tried with python 3 and got an error saying that the file was created with python 2 and an old version of hickle. Anyway, I installed python 2.7 and tried the same with it and now I am getting this error 

`C:\Python27\lib\site-packages\hickle\hickle.py:536: UserWarning: Hickle file is not versioned, attempting legacy loading...
  warnings.warn("Hickle file is not versioned, attempting legacy loading...")` 

Please help me with this as it is very urgent for me.
Solution for any of the above problem will be helpful.
Thanks.

**Comment by 1313e** [comment]
The file will load just fine, it simply gives you a warning stating that it was not versioned (as this is something that was added later).
In case it does not load, there is no way we can figure out what version is required for it, as it was never saved.
